

CC		= g++
LDFLAGS 	= -lm -std=c++11
PROJECT		= GoalRegression
FILES		= main.cpp KbReader.cpp OperatorReader.cpp OperatorGenerator.cpp Operator.cpp

${PROJECT}:${FILES}
	${CC} ${CFLAGS} -o ${PROJECT} ${FILES} ${LDFLAGS}
